#!/bin/sh

export TZ="Europe/Helsinki"

if [ `hostname` = "kopsu.com" ]
then
    cgi_dir=/home/webadmin/kopsu.com/cgi-bin
    html_dir=/home/webadmin/kopsu.com/html
else
    cgi_dir=/hsphere/local/home/saberg/dlarah.org/cgi-bin
    html_dir=/hsphere/local/home/saberg/dlarah.org
fi

$cgi_dir/winds.py > $html_dir/winds_tmp.html

[ $? -eq 0 ] && cp $html_dir/winds_tmp.html $html_dir/winds.html

$cgi_dir/winds_ee.py > $html_dir/winds_ee_tmp.html

[ $? -eq 0 ] && cp $html_dir/winds_ee_tmp.html $html_dir/winds_ee.html

