#!/bin/sh

export TZ="Europe/Helsinki"

[ -d /home/webadmin/kopsu.com/cgi-bin ] && cgi_dir=/home/webadmin/kopsu.com/cgi-bin
[ -d /home/webadmin/kopsu.com/html ] && html_dir=/home/webadmin/kopsu.com/html

[ -d /hsphere/local/home/saberg/dlarah.org/cgi-bin ] && cgi_dir=/hsphere/local/home/saberg/dlarah.org/cgi-bin
[ -d /hsphere/local/home/saberg/dlarah.org ] && html_dir=/hsphere/local/home/saberg/dlarah.org

[ -d $HOME/public_html/cgi-bin ] && cgi_dir=$HOME/public_html/cgi-bin
[ -d $HOME/public_html ] && html_dir=$HOME/public_html

if uname -a | grep -q amzn
then
    cgi_dir=/var/www/cgi-bin
    html_dir=/var/www/html
fi

$cgi_dir/winds.py > $html_dir/winds_tmp.html

[ $? -eq 0 ] && iconv -f UTF-8 -t ISO-8859-1 < $html_dir/winds_tmp.html > $html_dir/winds.html

$cgi_dir/winds_ee.py > $html_dir/winds_ee_tmp.html

[ $? -eq 0 ] && iconv -f UTF-8 -t ISO-8859-1 < $html_dir/winds_ee_tmp.html > $html_dir/winds_ee.html

