AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification for WindUpdate
Resources:
  WindUpdate:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 80
      Role: 'arn:aws:iam::514307432574:role/service-role/WindUpdateRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
